# Generated by Django 5.1.6 on 2025-05-27 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MineInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('program_url', models.URLField()),
                ('head_name', models.CharField(max_length=100)),
                ('head_image', models.CharField(max_length=100)),
                ('head_email', models.EmailField(max_length=254)),
                ('manager_name', models.CharField(max_length=100)),
                ('manager_image', models.CharField(max_length=100)),
                ('manager_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('all_info', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMateInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mates', to='myApp2.programinfo2')),
            ],
        ),
    ]
