# Generated by Django 5.1.5 on 2025-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentProgram',
        ),
    ]
