# Generated by Django 5.1.6 on 2025-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0002_studentinfo_delete_studentprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('all_info', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
