# Generated by Django 5.1.5 on 2025-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo2',
            name='all_info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo2',
            name='info',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studentinfo2',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
