# Generated by Django 5.1.6 on 2025-05-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0002_alter_studentinfo2_all_info_alter_studentinfo2_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInfo2',
        ),
    ]
