# Generated by Django 5.1.6 on 2025-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myApp1', '0003_delete_studentinfo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
