# Generated by Django 5.1.6 on 2025-05-27 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CPU', 'Процессор'), ('GPU', 'Видеокарта'), ('RAM', 'Оперативная память'), ('SSD', 'Накопитель')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PCConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.ForeignKey(limit_choices_to={'category': 'CPU'}, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_orders', to='myApp1.component')),
                ('gpu', models.ForeignKey(limit_choices_to={'category': 'GPU'}, on_delete=django.db.models.deletion.CASCADE, related_name='gpu_orders', to='myApp1.component')),
                ('ram', models.ForeignKey(limit_choices_to={'category': 'RAM'}, on_delete=django.db.models.deletion.CASCADE, related_name='ram_orders', to='myApp1.component')),
                ('ssd', models.ForeignKey(limit_choices_to={'category': 'SSD'}, on_delete=django.db.models.deletion.CASCADE, related_name='ssd_orders', to='myApp1.component')),
            ],
        ),
    ]
