# Generated by Django 5.1.5 on 2025-05-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0005_component_pcconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhoIsDFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('text_2', models.CharField(max_length=255)),
                ('img', models.URLField()),
            ],
        ),
    ]
