# Generated by Django 5.1.6 on 2025-05-28 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp1', '0007_computerbuild_ssd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerbuild',
            name='cpu',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CPU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_cpu', to='myApp1.component'),
        ),
        migrations.AlterField(
            model_name='computerbuild',
            name='gpu',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'GPU'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_gpu', to='myApp1.component'),
        ),
        migrations.AlterField(
            model_name='computerbuild',
            name='ram',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'RAM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_ram', to='myApp1.component'),
        ),
        migrations.AlterField(
            model_name='computerbuild',
            name='ssd',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'SSD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_ssd', to='myApp1.component'),
        ),
    ]
